DROP TABLE IF EXISTS student_login;
DROP TABLE IF EXISTS teacher_login;

CREATE TABLE student_login(
id INTEGER PRIMARY KEY AUTOINCREMENT,
student_name TEXT UNIQUE NOT NULL,
student_password TEXT NOT NULL
);

CREATE TABLE teacher_login(
id INTEGER PRIMARY KEY AUTOINCREMENT,
teacher_name TEXT UNIQUE NOT NULL,
teacher_password TEXT NOT NULL
);

DROP TABLE IF EXISTS students;

CREATE TABLE students (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id INTEGER UNIQUE NOT NULL,
    class_name TEXT,
    student_number TEXT UNIQUE,
    FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE
);

DROP TABLE IF EXISTS teachers;

CREATE TABLE teachers (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id INTEGER UNIQUE NOT NULL,
    subject TEXT,
    FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE
);

DROP TABLE IF EXISTS grades;

CREATE TABLE grades (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    student_id INTEGER NOT NULL,
    subject TEXT NOT NULL,
    score INTEGER NOT NULL,
    FOREIGN KEY(student_id) REFERENCES students(id) ON DELETE CASCADE
);





